const names = require('./04-names')
const sayHi = require('./05-utils')
const data = require('./06-alternative-flavor')
require('./07-mind-grenade')
sayHi('PATRICIA')
sayHi(names.tracy)
sayHi(names.leah)